# Purpose: Defines the Argo CD application for Istio ingress gateway
# This deploys the gateway that handles external traffic entering the mesh
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway               # Name of the Argo CD application
  namespace: argocd                 # Must be deployed in the argocd namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Enables proper cleanup on deletion
spec:
  project: infrastructure           # References the Argo CD project defined in argocd-project.yaml
  source:
    # Official Istio Helm repository
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway                  # The gateway chart contains the ingress components
    targetRevision: 1.19.0          # Specific chart version for stability
    helm:
      valueFiles:
        - gateway-values.yaml    # Path to values file relative to this file
  destination:
    server: https://kubernetes.default.svc  # Deploy to the current cluster
    namespace: istio-ingress        # Target namespace for Istio gateway components
  syncPolicy:
    automated:
      prune: true                   # Remove resources that are no longer defined
      selfHeal: true                # Sync if there's a difference between desired and actual state
    syncOptions:
      - CreateNamespace=true        # Create the istio-ingress namespace if it doesn't exist