# Purpose: Enforces minimal labeling requirements with audit-only mode
# This policy suggests but doesn't enforce basic resource labeling
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: suggest-labels
  annotations:
    policies.kyverno.io/title: Suggest Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Suggests basic labeling for resources but doesn't block deployment.
spec:
  validationFailureAction: audit     # Changed from enforce to audit - will only log violations
  rules:
  - name: check-for-app-label
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "It's recommended to include at least an 'app' label for better resource organization"
      pattern:
        metadata:
          labels:
            app: "?*"   # Simplified to only require a basic 'app' label instead of Kubernetes recommended labels