# Purpose: Monitors image sources without blocking deployment
# This policy logs usage of non-trusted registries but doesn't prevent deployment
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: monitor-image-registries
  annotations:
    policies.kyverno.io/title: Monitor Image Registries
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Monitors container images sources without blocking deployment.
spec:
  validationFailureAction: audit     # Changed from enforce to audit - will only log violations
  rules:
  - name: monitor-registries
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Image from non-standard registry detected - review for security compliance"
      pattern:
        spec:
          containers:
          # Extended list of trusted registries and more permissive pattern
          # Now includes ECR, Azure CR, and GitHub containers plus all subdomain variations
          - image: "{{ regex_match('(docker.io|gcr.io|quay.io|k8s.gcr.io|*.gcr.io|ghcr.io|*.azurecr.io|*.ecr.*.amazonaws.com)/.*', '@') || true }}"